baseURL = 'http://cmrasys.com/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'C M Rasys'
theme = 'cmrasys'

paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  author = "Christopher Rasys"
  github = "https://github.com/Skrath/cmrasys.com"
  facebook = "https://www.facebook.com/cmrasys"
#   og_image = "/images/og.png"
  sitename = "C M Rasys"
  twitter = "@cmrasys"
  description = "I dunno, an author website I guess"

[taxonomies]
    category = 'categories'
    tag = 'tags'
    book = 'books'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[menu]
    [[menu.main]]
        name = "Home"
        identifier = 'home'
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Stuff"
        identifier = 'stuff'
        url = "/posts/"
        weight = 2
    [[menu.main]]
        parent = 'stuff'
        identifier = 'news'
        name = "News and Updates"
        url = "/posts/"
        weight = 1
    [[menu.main]]
        parent = 'stuff'
        identifier = 'writings'
        name = "Prose and Poetry"
        url = "/writings/"
        weight = 2
    [[menu.main]]
        parent = 'stuff'
        identifier = 'programming'
        name = "Development and Design"
        url = "/programming/"
        weight = 3
    [[menu.main]]
        name = "Meta"
        identifier = 'meta'
        url = "/tags/"
        weight = 3
    [[menu.main]]
        parent = 'meta'
        name = "Tags"
        identifier = 'tags'
        url = "/tags/"
        weight = 1
    [[menu.main]]
        parent = 'meta'
        name = "Categories"
        identifier = 'categories'
        url = "/categories/"
        weight = 2
    [[menu.main]]
        identifier = 'about'
        name = "About"
        url = "/about/"
        weight = 4
