baseURL = 'http://cmrasys.com/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'C M Rasys'
theme = 'cmrasys'

paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  author = "Christopher Rasys"
  github = "https://github.com/Skrath/cmrasys.com"
  facebook = "https://www.facebook.com/cmrasys"
#   og_image = "/images/og.png"
  sitename = "C M Rasys"
  twitter = "@cmrasys"
  description = "I dunno, an author website I guess"

[taxonomies]
    category = 'categories'
    tag = 'tags'
    book = 'books'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[menu]
    [[menu.main]]
        name = "Home"
        identifier = 'home'
        url = "/"
        weight = 1
        sub = 'yar'
    [[menu.main]]
        name = "Posts"
        identifier = 'posts'
        url = "/posts/"
        weight = 2
        sub = 'wut'
    [[menu.main]]
        parent = 'posts'
        identifier = 'sub'
        name = "Sub"
        url = "/sub/"
        weight = 1
    [[menu.main]]
        parent = 'posts'
        identifier = 'sub2'
        name = "Sub2"
        url = "/sub2/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        identifier = 'tags'
        url = "/tags/"
        weight = 3
        sub = 'bloop'
    [[menu.main]]
        identifier = 'beans'
        name = "Beans"
        url = "/beans/"
        weight = 4
        sub = 'bleep'
