baseURL = 'http://cmrasys.com/'
languageCode = 'en-us'
title = 'C M Rasys'
theme = 'cmrasys'

[taxonomies]
    category = 'categories'
    tag = 'tags'
    book = 'books'

[menu]
    [[menu.main]]
        name = "Home"
        identifier = 'home'
        url = "/"
        weight = 1
        sub = 'yar'
    [[menu.main]]
        name = "Posts"
        identifier = 'posts'
        url = "/posts/"
        weight = 2
        sub = 'wut'
    [[menu.main]]
        parent = 'posts'
        identifier = 'sub'
        name = "Sub"
        url = "/sub/"
        weight = 1
    [[menu.main]]
        parent = 'posts'
        identifier = 'sub2'
        name = "Sub2"
        url = "/sub2/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        identifier = 'tags'
        url = "/tags/"
        weight = 3
        sub = 'bloop'
    [[menu.main]]
        identifier = 'beans'
        name = "Beans"
        url = "/beans/"
        weight = 4
        sub = 'bleep'
